In [1]:
import sys

In [2]:
print("python version:" , sys.version)

python version: 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]


# For Loop examples:

In [3]:
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)


apple
banana
cherry


In [4]:
word = "Chanda"
for char in word:
    print(char)

C
h
a
n
d
a


In [5]:
for number in range(2):
    print(number)

0
1


# While loop Examples

In [6]:
i=1
n=int(input("Enter last number"))
sum= 0
while(i<=n):
    sum=sum + (i*i)
    i=i+1
print("total addition: ",sum)

Enter last number54
total addition:  53955


In [7]:
i=1
n=int(input("Enter last number"))
sum=0
while(i<=n):
    if(i%2==0):
        sum = sum+i
    i = i + 1
print("sum of even no: ", sum)

Enter last number56
sum of even no:  812


In [8]:
i=int(input("Enter number"))
sum=0
while(i>0):
    sum= sum + (i%10)
    i = i/10
print("sum of digits=", sum)

Enter number54
sum of digits= 10.0


# Lambda Function

In [14]:
def myfunc(n):
  return lambda a : a ** n

square = myfunc(2)

print(square(11))

121


# Filter Function:

In [15]:
ages = [5, 12, 17, 18, 24, 32]

def myFunc(x):
  if x < 18:
    return False
  else:
    return True

adults = filter(myFunc, ages)

for x in adults:
  print(x)

18
24
32


# Reduce unction

In [16]:


# importing functools for reduce() 
import functools 

# initializing list 
lis = [1, 3, 5, 6, 2] 

# using reduce to compute sum of list 
print("The sum of the list elements is : ", end="") 
print(functools.reduce(lambda a, b: a+b, lis)) 

# using reduce to compute maximum element from list 
print("The maximum element of the list is : ", end="") 
print(functools.reduce(lambda a, b: a if a > b else b, lis)) 


The sum of the list elements is : 17
The maximum element of the list is : 6


# map function

In [17]:

# Return double of n
def addition(n):
	return n + n

# We double all numbers using map()
numbers = (1, 2, 3, 4)
result = map(addition, numbers)
print(list(result))


[2, 4, 6, 8]


# List Methods

In [18]:
#Indes()

In [19]:
# list of animals 
Animals= ["cat", "dog", "tiger"] 
# searching positiion of dog 
print(Animals.index("dog"))

1


In [21]:
#insert()
mark = [12,34,56,78]
mark.insert(0,45)
mark

[45, 12, 34, 56, 78]

In [22]:
#append()
list = [2,4,6,8]
list.append(10)
list

[2, 4, 6, 8, 10]

In [24]:
#reverse()
# a list of numbers
list1 = [1, 2, 3, 4, 1, 2, 6] 
list1.reverse() 
print(list1) 


[6, 2, 1, 4, 3, 2, 1]


# Keys()

In [25]:
fruits = {"apple": 50, "banana": 20, "orange": 30}
# Get the keys of the dictionary
print(fruits.keys()) 

dict_keys(['apple', 'banana', 'orange'])


# values()

In [26]:
fruits = {"apple": 50, "banana": 20, "orange": 30}

print(fruits.values())

dict_values([50, 20, 30])


# items()

In [28]:
print(fruits.items())

dict_items([('apple', 50), ('banana', 20), ('orange', 30)])


# •  The union() method returns a new set that contains all the elements from both sets

In [29]:
set1 = {1, 2, 3, 4}
set2 = {3, 4, 5, 6}

print(set1.union(set2))

{1, 2, 3, 4, 5, 6}


# •  The intersection() method returns a new set that contains only the elements that are common to both sets. It is equivalent to using the & operator.

In [31]:
print(set1.intersection(set2)) 


{3, 4}


# A frozenset is a special type of set that is immutable, meaning it cannot be changed or modified once it is created. It can be used as a key in a dictionary or as an element of another set, unlike a regular set. A frozenset can be created by using the frozenset() function on an iterable object, such as a list, a tuple, or a set.

In [32]:
fruits = ["apple", "banana", "orange"]
frozen_fruits = frozenset(fruits)
print(frozen_fruits)
frozen_fruits.add("cherry")

frozenset({'banana', 'orange', 'apple'})


AttributeError: 'frozenset' object has no attribute 'add'

# Decoders

In [33]:

def shout(text): 
	return text.upper() 

print(shout('Hello')) 

yell = shout 

print(yell('Hello')) 


HELLO
HELLO


# List comprehension

In [34]:
fruits = ["apple", "banana", "cherry", "kiwi", "mango"]
newlist = []

for x in fruits:
  if "a" in x:
    newlist.append(x)

print(newlist)

['apple', 'banana', 'mango']


# hstack()

In [35]:

# hstack() function 

import numpy as np 

# input array 
in_arr1 = np.array([ 1, 2, 3] ) 
print ("1st Input array : \n", in_arr1) 

in_arr2 = np.array([ 4, 5, 6] ) 
print ("2nd Input array : \n", in_arr2) 

# Stacking the two arrays horizontally 
out_arr = np.hstack((in_arr1, in_arr2)) 
print ("Output horizontally stacked array:\n ", out_arr) 


1st Input array : 
 [1 2 3]
2nd Input array : 
 [4 5 6]
Output horizontally stacked array:
  [1 2 3 4 5 6]


# Vstack()

In [38]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a, b))


array([[1, 2, 3],
       [4, 5, 6]])

# Zeros()

In [43]:
a=np.zeros(2)
a

array([0., 0.])

# ones()

In [46]:
a=np.ones((3,3),int)
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

# eye()

In [48]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# diag()

In [50]:
b=np.diag(a)
b

array([1., 1., 1., 1.])

# randint()

In [52]:
b=np.random.randint(2,5,6)
b

array([2, 3, 3, 2, 4, 4])

# rand()

In [53]:
c=np.random.rand(3)
c

array([0.21142938, 0.66183383, 0.98435155])

# seed()

In [56]:
np.random.seed(45)
a=np.random.rand(6)
a

array([0.98901151, 0.54954473, 0.2814473 , 0.07728957, 0.4444695 ,
       0.47280797])

# linspace()

In [57]:
i = np.linspace(0, 10, 5)
print(i)

[ 0.   2.5  5.   7.5 10. ]


# unique()

In [58]:
j = np.array([1, 2, 3, 2, 4, 1, 5, 6, 4])
k = np.unique(j)
print(k)

[1 2 3 4 5 6]


# reshape()

In [64]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
a=a.reshape(4,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

# argmin()

In [69]:
b=np.argmax(a,axis=0)
b

array([3, 3, 3], dtype=int64)

# agrmax()

In [70]:
c=np.argmax(a,axis=1)
c

array([2, 2, 2, 2], dtype=int64)